// classics-notes.js — curated { local (native script), note:{en,fr}, sources }
// for nation-overlay "classic" dishes, keyed by ISO country code then dish name.
//
// Every entry is WEB-SOURCED and adversarially source-verified (non-inventive):
// drafted from a credited source (NLB Infopedia, Roots.gov.sg, Michelin Guide,
// TasteAtlas, established food media), then a second pass checked the fact +
// native script against the source and trimmed each note to <=140 chars.
// Generated by the curate-classics workflow; APPEND new country batches here.
// Consumed by city-plates.js _overlayDishMeta() so the "More classics" list
// opens an explanation card (the operator: "each classic must have an explanation").
//
// v0.62.175 — SG batch 1 (30 zi-char / hawker classics).

const CLASSIC_NOTES = {
  "SG": {
    "chilli crab": {
      "local": "辣椒螃蟹",
      "note": {
        "en": "Singapore's iconic dish: mud crab stir-fried in a sweet-savoury tomato-chilli gravy, credited to Cher Yam Tian's mid-1950s pushcart stall.",
        "fr": "Plat phare de Singapour : crabe de vase saute dans une sauce tomate-piment douce-salee, attribue a Cher Yam Tian au milieu des annees 1950."
      },
      "sources": [
        {
          "name": "NLB Infopedia — Chilli crab",
          "url": "https://eresources.nlb.gov.sg/infopedia/articles/SIP_1112_2011-06-17.html"
        },
        {
          "name": "Chilli Crab — Roots.gov.sg (National Heritage Board)",
          "url": "https://www.roots.gov.sg/ich-landing/ich/chilli-crab"
        }
      ]
    },
    "black pepper crab": {
      "local": "黑胡椒蟹",
      "note": {
        "en": "Singaporean dish of hard-shell crab stir-fried with crushed black pepper and garlic; created by Long Beach Seafood, drier than chilli crab.",
        "fr": "Plat singapourien de crabe sauté au poivre noir concassé et ail; créé par Long Beach Seafood, plus sec que le chilli crab."
      },
      "sources": [
        {
          "name": "Long Beach Seafood Restaurant - Wikipedia",
          "url": "https://en.wikipedia.org/wiki/Long_Beach_Seafood_Restaurant"
        },
        {
          "name": "Black pepper crab - Wikipedia",
          "url": "https://en.wikipedia.org/wiki/Black_pepper_crab"
        }
      ]
    },
    "cereal prawns": {
      "local": "麦片虾",
      "note": {
        "en": "Singapore zichar dish: shell-on tiger prawns deep-fried, then tossed in crisp Nestum cereal, curry leaves, bird's eye chillies and butter.",
        "fr": "Plat zichar singapourien : grosses crevettes frites en carapace, sautées au Nestum croustillant, feuilles de curry, piment et beurre."
      },
      "sources": [
        {
          "name": "Singapore Noodles (Pamelia Chia) - Cereal Prawns",
          "url": "https://sgpnoodles.substack.com/p/cereal-prawns"
        },
        {
          "name": "TasteAtlas - Cereal Prawns",
          "url": "https://www.tasteatlas.com/cereal-prawns"
        }
      ]
    },
    "salted egg yolk crab": {
      "local": "咸蛋黄炒蟹",
      "note": {
        "en": "Singapore zi char dish: deep-fried mud crab tossed in a buttery mashed salted-duck-egg-yolk sauce with curry leaves and chilli padi.",
        "fr": "Plat zi char singapourien : crabe de vase frit enrobé d'une sauce beurrée au jaune d'œuf de cane salé, feuilles de curry et piment."
      },
      "sources": [
        {
          "name": "epicure Magazine - Best salted egg yolk crabs in Singapore",
          "url": "https://www.epicureasia.com/food/1944/best-salted-egg-yolk-crabs-in-singapore/"
        },
        {
          "name": "DanielFoodDiary - 12 Salted Egg National Dishes in Singapore",
          "url": "https://danielfooddiary.com/2017/07/29/saltedeggshiok/"
        }
      ]
    },
    "salted egg fish skin": {
      "local": "咸蛋鱼皮",
      "note": {
        "en": "Singaporean zichar snack: crispy fried fish skin in creamy salted-egg-yolk sauce with curry leaves and chilli; now a packaged snack.",
        "fr": "Snack zichar singapourien : peau de poisson frite croustillante en sauce crémeuse au jaune d'oeuf salé, feuilles de curry et piment."
      },
      "sources": [
        {
          "name": "Michelin Guide Singapore — The Secrets Behind Salted Egg Fish Skin Snacks",
          "url": "https://guide.michelin.com/sg/en/article/people/5-questions-with-the-founders-of-crusty-s-on-the-secrets-behind-salted-egg-fish-skin-snacks"
        },
        {
          "name": "ieatishootipost — Yam's Treasures: Inventor of Salted Egg Fish Skin",
          "url": "https://ieatishootipost.sg/yams-treasures-inventor-of-salted-egg-fish-skin-and-other-zi-char-classics/"
        }
      ]
    },
    "butter prawns": {
      "local": "奶油虾",
      "note": {
        "en": "Malaysian-Chinese tze char prawns in butter, garlic and curry leaves, finished with crispy egg/coconut floss or creamy evaporated milk.",
        "fr": "Plat sino-malais (tze char) de crevettes au beurre, ail et feuilles de curry, avec floss d'oeuf croustillant ou lait concentre cremeux."
      },
      "sources": [
        {
          "name": "Rasa Malaysia – Butter Prawn",
          "url": "https://rasamalaysia.com/butter-prawn/"
        },
        {
          "name": "Nyonya Cooking – Butter Prawns",
          "url": "https://www.nyonyacooking.com/recipes/butter-prawns~ryACDwoDM5-7"
        }
      ]
    },
    "coffee pork ribs": {
      "local": "咖啡排骨",
      "note": {
        "en": "Singaporean zi char dish of deep-fried pork ribs glazed in a sticky sweet-savoury coffee sauce; popularised by chef Sam Leong.",
        "fr": "Plat singapourien zi char de cotes de porc frites nappees d'une sauce au cafe sucree-salee collante; popularise par le chef Sam Leong."
      },
      "sources": [
        {
          "name": "The Burning Kitchen - Sticky Coffee Pork Ribs (咖啡排骨)",
          "url": "https://theburningkitchen.com/sticky-coffee-kahlua-pork-ribs/"
        },
        {
          "name": "What To Cook Today - Singapore Coffee Pork Ribs (咖啡排骨)",
          "url": "https://whattocooktoday.com/singapore-coffee-pork-ribs.html"
        }
      ]
    },
    "marmite chicken": {
      "local": "妈蜜鸡",
      "note": {
        "en": "Singapore zi-char favourite: crispy fried chicken tossed in a sweet-savoury glaze of Marmite yeast extract, soy, honey and maltose.",
        "fr": "Plat phare des zi-char de Singapour : poulet frit croustillant nappe d'un glacage sucre-sale a base de Marmite, soja, miel et maltose."
      },
      "sources": [
        {
          "name": "Taste of Asian Food - Marmite Chicken (妈蜜鸡)",
          "url": "https://tasteasianfood.com/marmite-chicken/"
        },
        {
          "name": "Daniel Food Diary - Best Zi Char Eateries in Singapore",
          "url": "https://danielfooddiary.com/2024/02/03/zichareateries/"
        }
      ]
    },
    "honey pork ribs": {
      "local": "蜜汁排骨",
      "note": {
        "en": "Cantonese pork ribs braised tender, glazed with maltose and grilled hot for a sticky, glossy, charred finish; a Singapore zi char staple.",
        "fr": "Travers de porc cantonais braisés, glacés au maltose et grillés vif pour un fini collant et caramélisé; classique du zi char singapourien."
      },
      "sources": [
        {
          "name": "The Burning Kitchen — Sticky Chinese Honey Pork Ribs (蜜汁排骨)",
          "url": "https://theburningkitchen.com/honey-bbq-pork-rib-recipe/"
        },
        {
          "name": "LadyIronChef — A Guide to Zi Char",
          "url": "https://www.ladyironchef.com/2016/05/zi-char-guide/"
        }
      ]
    },
    "sambal kangkong": {
      "local": "马来风光",
      "note": {
        "en": "Water spinach (kangkong) stir-fried over high heat with sambal and belacan (shrimp paste); a Malay-origin zi char staple in Singapore.",
        "fr": "Liseron d'eau (kangkong) sauté à feu vif au sambal et au belacan (pâte de crevettes); plat zi char d'origine malaise prisé à Singapour."
      },
      "sources": [
        {
          "name": "Noob Cook Recipes — Sambal Kangkong 马来风光",
          "url": "https://noobcook.com/sambal-kangkong/"
        },
        {
          "name": "The Burning Kitchen — Spicy Water Spinach (Sambal Kangkong/马来风光)",
          "url": "https://theburningkitchen.com/sambal-kangkong/"
        }
      ]
    },
    "sambal sotong": {
      "local": "sambal sotong",
      "note": {
        "en": "Squid stir-fried in a Malay/Peranakan sambal of chilli, belacan and tamarind; a hawker and zi char favourite.",
        "fr": "Calmar sauté dans un sambal malais/peranakan de piment, belacan (pâte de crevette) et tamarin; favori des hawkers et zi char."
      },
      "sources": [
        {
          "name": "Share Food Singapore - Sambal Sotong",
          "url": "https://www.sharefood.sg/cuisine/asian/sambal-sotong/"
        }
      ]
    },
    "sambal stingray": {
      "local": "Ikan Pari Bakar",
      "note": {
        "en": "Stingray fins coated in chilli sambal, wrapped in banana leaf and charcoal-grilled; a Malay-origin hawker staple served with lime.",
        "fr": "Ailerons de raie au sambal piment, grillés en feuille de bananier sur charbon; plat malais de hawker servi avec citron vert."
      },
      "sources": [
        {
          "name": "Sambal stingray - Wikipedia",
          "url": "https://en.wikipedia.org/wiki/Sambal_stingray"
        }
      ]
    },
    "fish head curry": {
      "local": "மீன் தலைக் கறி",
      "note": {
        "en": "Indian-Chinese fusion created in 1950s Singapore by Kerala migrant M.J. Gomez, who set South Indian curry on a fish head for Chinese diners.",
        "fr": "Fusion indo-chinoise créée dans le Singapour des années 1950 par M.J. Gomez, du Kerala, posant un curry sud-indien sur une tête de poisson."
      },
      "sources": [
        {
          "name": "NLB Infopedia — Fish head curry",
          "url": "https://eresources.nlb.gov.sg/infopedia/articles/SIP_624_2005-01-04.html"
        },
        {
          "name": "Roots.gov.sg — Fish Head Curry (ICH)",
          "url": "https://www.roots.gov.sg/ich-landing/ich/fish-head-curry"
        }
      ]
    },
    "cereal butter chicken": {
      "local": "麦片鸡",
      "note": {
        "en": "Singapore zi char dish: crispy fried chicken tossed in butter, curry leaves, chili and toasted Nestum cereal; spin on cereal butter prawns.",
        "fr": "Plat zi char singapourien : poulet frit croustillant, beurre, curry, piment, céréales Nestum grillées ; variante des crevettes au beurre."
      },
      "sources": [
        {
          "name": "What To Cook Today — Cereal Butter Fried Chicken (Mai Pian Ji)",
          "url": "https://whattocooktoday.com/cereal-butter-fried-chicken-mai-pian-ji.html"
        },
        {
          "name": "Nestlé Singapore — Cereal Chicken recipe with Nestum",
          "url": "https://www.nestle.com.sg/brands/recipes/nestle-nestum/cereal-chicken"
        }
      ]
    },
    "drunken prawns": {
      "local": "醉虾",
      "note": {
        "en": "Fresh prawns steamed or poached in Chinese rice wine (Shaoxing/Hua Diao); Singapore's popular version adds herbs like goji and red dates.",
        "fr": "Crevettes fraiches cuites au vin de riz chinois (Shaoxing/Hua Diao); la version singapourienne y ajoute baies de goji et dattes rouges."
      },
      "sources": [
        {
          "name": "Wikipedia - Drunken shrimp",
          "url": "https://en.wikipedia.org/wiki/Drunken_shrimp"
        },
        {
          "name": "TasteAtlas - Drunken Prawn (Zui Xia)",
          "url": "https://www.tasteatlas.com/drunken-prawn"
        }
      ]
    },
    "yam ring": {
      "local": "芋头圈",
      "note": {
        "en": "Deep-fried ring of mashed taro filled with stir-fried meat or seafood; by chef Hooi Kok Wai of Singapore's Dragon Phoenix Restaurant.",
        "fr": "Anneau de taro frit garni de viande ou fruits de mer sautes; du chef Hooi Kok Wai du Dragon Phoenix de Singapour."
      },
      "sources": [
        {
          "name": "Wikipedia - Yam ring",
          "url": "https://en.wikipedia.org/wiki/Yam_ring"
        }
      ]
    },
    "hor fun (san lou)": {
      "local": "三捞河粉",
      "note": {
        "en": "Cantonese-rooted Singapore zi char dish: flat rice noodles tossed (\"san lou\") with fish slices and beansprouts in light wok-hei gravy.",
        "fr": "Plat zi char singapourien d'origine cantonaise : nouilles de riz plates sautees (\"san lou\") au poisson et germes, sauce claire au wok-hei."
      },
      "sources": [
        {
          "name": "What To Cook Today — San Lau Hor Fun (Three-tossed Flat Rice Noodles)",
          "url": "https://whattocooktoday.com/san-lau-hor-fun.html"
        },
        {
          "name": "Carry It Like Harry — Sam Lou Hor Fan 三捞河粉",
          "url": "https://carryitlikeharry.com/sam-lou-hor-fan-%E4%B8%89%E6%8D%9E%E6%B2%B3%E7%B2%89/"
        }
      ]
    },
    "wat tan hor": {
      "local": "滑蛋河",
      "note": {
        "en": "Cantonese-style wok-fried flat rice noodles (hor fun) blanketed in a silky egg gravy with seafood and meat; 'wat tan' means silky egg.",
        "fr": "Nouilles de riz plates (hor fun) sautees au wok, nappees d'une sauce a l'oeuf soyeuse, fruits de mer et viande; wat tan = oeuf soyeux."
      },
      "sources": [
        {
          "name": "Taste of Asian Food — Wat Tan Hor (滑旦河)",
          "url": "https://tasteasianfood.com/wat-tan-hor/"
        },
        {
          "name": "What To Cook Today — Wat Tan Hor Fun",
          "url": "https://whattocooktoday.com/kwe-tiau-siram-wat-tan-hor.html"
        }
      ]
    },
    "chicken curry SG style": {
      "local": "kari ayam",
      "note": {
        "en": "Singapore-style curry chicken: a fragrant rempah-and-coconut-milk gravy with potatoes, fusing Chinese, Malay and Indian spice traditions.",
        "fr": "Poulet au curry singapourien : sauce parfumée au rempah et lait de coco, pommes de terre, fusion d'épices chinoises, malaises et indiennes."
      },
      "sources": [
        {
          "name": "Vittles — Pamelia Chia's Curry Chicken",
          "url": "https://www.vittlesmagazine.com/p/pamelia-chias-curry-chicken"
        },
        {
          "name": "Rasa Malaysia — Chicken Curry with Potatoes",
          "url": "https://rasamalaysia.com/chicken-curry-with-potatoes/"
        }
      ]
    },
    "hainanese curry rice": {
      "local": "海南咖喱饭",
      "note": {
        "en": "Singapore dish by Hainanese chefs: rice drenched in thick curry with British-style pork chop, Peranakan chap chye and Indian-spiced gravy.",
        "fr": "Plat singapourien de chefs hainanais : riz nappe d'un curry epais, cotelette de porc panee, chap chye peranakan et sauce epicee indienne."
      },
      "sources": [
        {
          "name": "Roots.gov.sg (National Heritage Board, Singapore)",
          "url": "https://www.roots.gov.sg/ich-landing/ich/hainanese-curry-rice"
        },
        {
          "name": "Wikipedia: Hainanese curry rice",
          "url": "https://en.wikipedia.org/wiki/Hainanese_curry_rice"
        }
      ]
    },
    "singapore noodles (curry bee hoon)": {
      "local": "咖喱米粉",
      "note": {
        "en": "Rice vermicelli stir-fried or served in a laksa-like curry; a Singapore hawker staple distinct from Hong Kong-invented \"Singapore noodles.\"",
        "fr": "Vermicelles de riz sautés ou en curry façon laksa; plat de hawker singapourien, distinct des \"nouilles de Singapour\" nées à Hong Kong."
      },
      "sources": [
        {
          "name": "SBS Food — The curious case of Singapore noodles",
          "url": "https://www.sbs.com.au/food/article/2021/05/06/not-made-singapore-curious-case-singapore-noodles"
        },
        {
          "name": "Michelin Guide — Early Morning Economic Bee Hoon",
          "url": "https://guide.michelin.com/sg/en/article/dining-out/breakfast-club-early-morning-economic-bee-hoon"
        }
      ]
    },
    "bak chor mee": {
      "local": "肉脞面",
      "note": {
        "en": "Hokkien for \"minced meat noodles\"; Singapore's Teochew-rooted dish: mee pok tossed in chilli, lard and black-vinegar sauce with minced pork.",
        "fr": "\"Nouilles au porc hache\" en hokkien; plat singapourien d'origine teochew: mee pok au piment, saindoux et vinaigre noir, porc hache."
      },
      "sources": [
        {
          "name": "SG101 (National Heritage, gov.sg) — Bak Chor Mee",
          "url": "https://www.sg101.gov.sg/resources/archives/heritage-bak-chor-mee/"
        },
        {
          "name": "Michelin Guide Singapore — Bak Chor Mee",
          "url": "https://guide.michelin.com/sg/en/article/dining-out/iconic-dishes-hill-street-tai-hwa-bak-chor-mee"
        }
      ]
    },
    "wanton mee dry": {
      "local": "云吞面 (干)",
      "note": {
        "en": "Cantonese egg noodles tossed dry in sauce (less soy than Malaysia, often chilli/ketchup), char siu and cai-xin; wontons apart in soup.",
        "fr": "Nouilles aux oeufs cantonaises sautees a sec (moins de soja qu'en Malaisie, souvent piment), char siu et cai-xin; wontons a part en soupe."
      },
      "sources": [
        {
          "name": "Wonton noodles - Wikipedia",
          "url": "https://en.wikipedia.org/wiki/Wonton_noodles"
        },
        {
          "name": "20 Best Wonton Mee In Singapore - Eatbook",
          "url": "https://eatbook.sg/wonton-mee-singapore/"
        }
      ]
    },
    "wanton mee soup": {
      "local": "云吞面（汤）",
      "note": {
        "en": "Cantonese-origin soup: thin egg noodles, pork-chicken broth, wonton dumplings, char siew, leafy greens; SG version uses less soy than HK.",
        "fr": "Soupe cantonaise : nouilles fines aux oeufs, bouillon porc-poulet, raviolis wonton, char siew, legumes; version SG moins de soja qu'a HK."
      },
      "sources": [
        {
          "name": "Wikipedia — Wonton noodles",
          "url": "https://en.wikipedia.org/wiki/Wonton_noodles"
        },
        {
          "name": "Eatbook SG — Best Wonton Mee in Singapore",
          "url": "https://eatbook.sg/wonton-mee-singapore/"
        }
      ]
    },
    "char siu rice": {
      "local": "叉燒飯",
      "note": {
        "en": "Cantonese-style 'fork roasted' (叉燒) barbecued pork, glazed with maltose or honey, sliced over rice with cucumber, sweet gravy or dark soy.",
        "fr": "Porc barbecue cantonais « rôti à la fourchette » (叉燒), glacé au maltose ou miel, tranché sur riz avec concombre, sauce sucrée ou soja noir."
      },
      "sources": [
        {
          "name": "Char siu - Wikipedia",
          "url": "https://en.wikipedia.org/wiki/Char_siu"
        },
        {
          "name": "13 Char Siew Rice In Singapore - Eatbook",
          "url": "https://eatbook.sg/char-siew-rice/"
        }
      ]
    },
    "roast meat rice (siu mei)": {
      "local": "烧味",
      "note": {
        "en": "Cantonese spit-roasted meats (char siew, roast pork, roast duck) over rice; sold at Singapore siu laap stalls in every hawker centre.",
        "fr": "Viandes cantonaises rôties à la broche (char siew, porc, canard) sur du riz; vendues aux stands siu laap de tout hawker singapourien."
      },
      "sources": [
        {
          "name": "Siu mei - Wikipedia",
          "url": "https://en.wikipedia.org/wiki/Siu_mei"
        },
        {
          "name": "11 best roast meat stalls in Singapore - SETHLUI.com",
          "url": "https://sethlui.com/roast-meat-stalls-food-guide-singapore/"
        }
      ]
    },
    "lor mee": {
      "local": "卤面",
      "note": {
        "en": "Hokkien hawker dish of flat yellow noodles in a thick, starch-thickened five-spice braised gravy, topped with egg, fish cake and ngoh hiang.",
        "fr": "Plat hokkien de nouilles jaunes plates dans une sauce braisée épaisse au cinq-épices, garnie d'œuf, de gâteau de poisson et de ngoh hiang."
      },
      "sources": [
        {
          "name": "SG101 (Singapore Government heritage archive) — Lor Mee in Singapore",
          "url": "https://www.sg101.gov.sg/resources/archives/heritage-lor-mee-in-singapore/"
        },
        {
          "name": "Wikipedia — Lor mee",
          "url": "https://en.wikipedia.org/wiki/Lor_mee"
        }
      ]
    },
    "fishball noodle": {
      "local": "鱼圆面",
      "note": {
        "en": "Teochew-origin Chinese hawker dish: springy fishballs with egg noodles (often flat mee pok), served dry in chili-vinegar sauce or in soup.",
        "fr": "Plat chinois teochew : boulettes de poisson sur nouilles aux oeufs (souvent mee pok plates), servi sec en sauce piment-vinaigre ou en soupe."
      },
      "sources": [
        {
          "name": "SETHLUI.com — fishball noodles guide Singapore",
          "url": "https://sethlui.com/fishball-noodles-guide-singapore/"
        },
        {
          "name": "DanielFoodDiary.com — Fishball Meepok in Singapore",
          "url": "https://danielfooddiary.com/2020/02/04/fishballnoodles/"
        }
      ]
    },
    "mee pok dry": {
      "local": "面薄 (干捞)",
      "note": {
        "en": "Flat yellow Teochew noodles, tossed dry (\"tah\") in chilli-vinegar-soy sauce instead of broth, topped with minced pork, liver and meatballs.",
        "fr": "Nouilles plates et jaunes teochew, sautées à sec (« tah ») dans une sauce piment-vinaigre-soja, garnies de porc haché, foie et boulettes."
      },
      "sources": [
        {
          "name": "Mee pok - Wikipedia",
          "url": "https://en.wikipedia.org/wiki/Mee_pok"
        },
        {
          "name": "Eatbook SG - Best Bak Chor Mee",
          "url": "https://eatbook.sg/best-bak-chor-mee-singapore/"
        }
      ]
    },
    "yong tau foo": {
      "local": "酿豆腐",
      "note": {
        "en": "Hakka dish of tofu and vegetables stuffed with fish paste or minced meat; \"yong\" means \"to stuff.\" A Singapore hawker staple.",
        "fr": "Plat hakka de tofu et legumes farcis de pate de poisson ou viande hachee ; \"yong\" signifie \"farcir.\" Un classique des hawkers de Singapour."
      },
      "sources": [
        {
          "name": "Michelin Guide Singapore — What is Yong Tau Foo",
          "url": "https://guide.michelin.com/sg/en/article/features/what-is-yong-tau-foo"
        },
        {
          "name": "Wikipedia — Yong tau foo",
          "url": "https://en.wikipedia.org/wiki/Yong_tau_foo"
        }
      ]
    }
  }
};

module.exports = { CLASSIC_NOTES };
