// count-recount.js — v0.61.164
//
// Per-item recount functions for the `/ver Periodical` owner
// sub-menu. Each function counts its data source, records the
// result via `count-history.recordCount`, and returns
// `{ item, n, source, ts }` (the new entry) or `null` on failure.
//
// All 14 items the operator listed for v0.61.164. Each function is
// defensively wrapped so a missing module or unreachable API never
// throws; failures record `n=null, source='unavailable'` so the
// history surfaces the gap.
//
// Re-count strategies:
//   - Curated arrays / JSON files: read the file, count the
//     entries (or trust `_meta.featureCount` when present).
//   - LTA-fetched (carparks, bus-stops): call the existing
//     module's fetcher.
//
// A `runAll(redis, opts)` orchestrator runs every item in parallel.
// The v0.61.165 chat UI binds individual recount fns to its
// `Re-check` buttons; the v0.61.166 cron scheduler calls runAll on
// the per-item cadence.

'use strict';

const fs = require('fs');
const path = require('path');

const { recordCount } = require('./count-history');

// Helper — count records in a `data/geo-*.json` overlay file.
// These files were generated by `scripts/build-geo-overlays.js`
// from the data.gov.sg geojson originals. Each carries a
// `_meta.featureCount` field; we prefer that, then fall back to
// `features.length`. Returns null when the file is missing or
// unparseable.
function _countGeoOverlay(relPath) {
  try {
    const abs = path.join(__dirname, relPath);
    const raw = fs.readFileSync(abs, 'utf8');
    const j = JSON.parse(raw);
    if (j && j._meta && Number.isFinite(j._meta.featureCount)) {
      return j._meta.featureCount;
    }
    if (j && Array.isArray(j.features)) return j.features.length;
    return null;
  } catch {
    return null;
  }
}

// Helper — count entries in a plain JSON array file under data/.
function _countJsonArray(relPath, arrayKey = null) {
  try {
    const abs = path.join(__dirname, relPath);
    const raw = fs.readFileSync(abs, 'utf8');
    const j = JSON.parse(raw);
    if (arrayKey && j && Array.isArray(j[arrayKey])) return j[arrayKey].length;
    if (Array.isArray(j)) return j.length;
    if (j && Array.isArray(j.features)) return j.features.length;
    if (j && Array.isArray(j.centres)) return j.centres.length;
    return null;
  } catch {
    return null;
  }
}

// ---- Per-item recount fns -----------------------------------------

async function recountCuisines(redis, opts = {}) {
  let n = null;
  try {
    const cv = require('./cuisines-vault');
    const list = cv.getAllCuisines();
    if (Array.isArray(list)) n = list.length;
  } catch { /* module-missing → n stays null */ }
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'cuisines', n ?? 0, source, opts.notes || '');
  return { item: 'cuisines', n, source };
}

async function recountMichelin(redis, opts = {}) {
  let n = null;
  try {
    const m = require('./michelin-2025');
    if (typeof m.getAll === 'function') n = m.getAll().length;
  } catch { /* */ }
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'michelin', n ?? 0, source, opts.notes || '');
  return { item: 'michelin', n, source };
}

async function recountHawker(redis, opts = {}) {
  // Hawker vault parses the curated MD; count the data/hawker-centres.json
  // generated artefact for the live number. Falls back to the vault
  // module's parse if the file is missing.
  let n = _countJsonArray('data/hawker-centres.json');
  if (n == null) {
    try {
      const hv = require('./hawker-vault');
      if (typeof hv.getAll === 'function') n = hv.getAll().length;
      else if (Array.isArray(hv.CENTRES)) n = hv.CENTRES.length;
    } catch { /* */ }
  }
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'hawker', n ?? 0, source, opts.notes || '');
  return { item: 'hawker', n, source };
}

async function recountHealthierEateries(redis, opts = {}) {
  const n = _countJsonArray('data/healthier-eateries.json');
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'healthier-eateries', n ?? 0, source, opts.notes || '');
  return { item: 'healthier-eateries', n, source };
}

async function recountBuildings(redis, opts = {}) {
  // Two curated sources: `data/buildings.json` (newer) and
  // `data/directory-buildings.json` (legacy). Prefer the newer one.
  let n = _countJsonArray('data/buildings.json');
  if (n == null) n = _countJsonArray('data/directory-buildings.json');
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'buildings', n ?? 0, source, opts.notes || '');
  return { item: 'buildings', n, source };
}

async function recountBusStops(redis, opts = {}) {
  // LTA bus stops live in Redis after the first transport.refreshStops
  // call (ZSET `lta:busstops:geo`, ~5500 members). When Redis isn't
  // open OR the cache hasn't warmed yet, fall back to the curated
  // `geoloc/LTABusStop.geojson` count via the json-array helper.
  let n = null;
  if (redis && redis.isOpen) {
    try {
      n = await redis.zCard('lta:busstops:geo');
      if (!Number.isFinite(n) || n <= 0) n = null;
    } catch { n = null; }
  }
  if (n == null) {
    // Curated geojson (operator-curated baseline).
    try {
      const abs = path.join(__dirname, 'geoloc', 'LTABusStop.geojson');
      const raw = fs.readFileSync(abs, 'utf8');
      const j = JSON.parse(raw);
      if (j && Array.isArray(j.features)) n = j.features.length;
    } catch { /* */ }
  }
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'bus-stops', n ?? 0, source, opts.notes || '');
  return { item: 'bus-stops', n, source };
}

async function recountTrainStations(redis, opts = {}) {
  const n = _countJsonArray('data/mrt-coords.json');
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'train-stations', n ?? 0, source, opts.notes || '');
  return { item: 'train-stations', n, source };
}

async function recountTrainLines(redis, opts = {}) {
  // Derive line count from the station codes' first prefix
  // (e.g. NS, EW, CC, NE, DT, TE, BP, JE, JW). The JB RTS Link
  // (Dec 2026 / Jun 2027) will get its own prefix; this recount
  // surfaces it automatically once LTA exposes the stations.
  let n = null;
  try {
    const abs = path.join(__dirname, 'data', 'mrt-coords.json');
    const raw = fs.readFileSync(abs, 'utf8');
    const j = JSON.parse(raw);
    const features = Array.isArray(j) ? j : (Array.isArray(j?.features) ? j.features : []);
    const lines = new Set();
    for (const f of features) {
      const code = String((f?.code) || (f?.properties?.code) || '').toUpperCase().trim();
      // Strip the trailing digits to get the line prefix.
      const m = code.match(/^[A-Z]{2,3}/);
      if (m) lines.add(m[0]);
    }
    n = lines.size > 0 ? lines.size : null;
  } catch { /* */ }
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'train-lines', n ?? 0, source, opts.notes || '');
  return { item: 'train-lines', n, source };
}

async function recountCarparks(redis, opts = {}) {
  // LTA carparks are live-fetched via carpark.fetchAll. Each search
  // would hit the API; for a periodical recount that's fine (one
  // page on cadence). Falls back to null on quota / network error.
  let n = null;
  try {
    const cp = require('./carpark');
    if (typeof cp.allPoints === 'function') {
      const list = await cp.allPoints();
      if (Array.isArray(list)) n = list.length;
    }
  } catch { /* */ }
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'carparks', n ?? 0, source, opts.notes || '');
  return { item: 'carparks', n, source };
}

async function recountParks(redis, opts = {}) {
  const n = _countGeoOverlay('data/geo-parks.json');
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'parks', n ?? 0, source, opts.notes || '');
  return { item: 'parks', n, source };
}

async function recountAttractions(redis, opts = {}) {
  const n = _countGeoOverlay('data/geo-attractions.json');
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'attractions', n ?? 0, source, opts.notes || '');
  return { item: 'attractions', n, source };
}

async function recountClinics(redis, opts = {}) {
  const n = _countGeoOverlay('data/geo-clinics.json');
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'clinics', n ?? 0, source, opts.notes || '');
  return { item: 'clinics', n, source };
}

async function recountHospitals(redis, opts = {}) {
  const n = _countGeoOverlay('data/geo-hospitals.json');
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'hospitals', n ?? 0, source, opts.notes || '');
  return { item: 'hospitals', n, source };
}

async function recountPolice(redis, opts = {}) {
  const n = _countGeoOverlay('data/geo-police.json');
  const source = n == null ? 'unavailable' : (opts.source || 'manual');
  await recordCount(redis, 'police', n ?? 0, source, opts.notes || '');
  return { item: 'police', n, source };
}

// ---- Dispatch table + runAll --------------------------------------

const RECOUNTERS = Object.freeze({
  'cuisines':            recountCuisines,
  'michelin':            recountMichelin,
  'hawker':              recountHawker,
  'healthier-eateries':  recountHealthierEateries,
  'buildings':           recountBuildings,
  'bus-stops':           recountBusStops,
  'train-stations':      recountTrainStations,
  'train-lines':         recountTrainLines,
  'carparks':            recountCarparks,
  'parks':               recountParks,
  'attractions':         recountAttractions,
  'clinics':             recountClinics,
  'hospitals':           recountHospitals,
  'police':              recountPolice
});

// Single-item dispatch. Returns `null` for unknown item ids.
async function recountOne(redis, item, opts = {}) {
  const fn = RECOUNTERS[item];
  if (typeof fn !== 'function') return null;
  return fn(redis, opts);
}

// Parallel recount of all 14 items. Returns
// `[{item, n, source}, ...]` in the order RECOUNTERS keys are
// enumerated. Per-item failures are isolated (each fn already
// records `source='unavailable'` and returns null-n on error).
async function recountAll(redis, opts = {}) {
  const items = Object.keys(RECOUNTERS);
  return Promise.all(items.map((it) => RECOUNTERS[it](redis, opts)));
}

module.exports = {
  RECOUNTERS,
  recountOne,
  recountAll,
  // exported per-item fns for tests + direct callers
  recountCuisines,
  recountMichelin,
  recountHawker,
  recountHealthierEateries,
  recountBuildings,
  recountBusStops,
  recountTrainStations,
  recountTrainLines,
  recountCarparks,
  recountParks,
  recountAttractions,
  recountClinics,
  recountHospitals,
  recountPolice
};
