// hawker-vault.js — v0.50.0 canonical hawker-centre vault from MD file.
//
// Source: data/list-of-hawker-centres.md (123 centres, snapshot 25 Jul 2025).
// The MD file is committed to the repo, so no network fetch needed —
// reads from disk at module load, parses once, cached in memory.
//
// Why MD over PDF (v0.49.0 → v0.50.0): the MD file is human-editable,
// reviewable in PR diffs, and doesn't need pdf-parse. Plus we get
// region segmentation (north/south/east/west/central) for free since
// each row carries an address + postal code.
//
// Schema per centre:
//   { sno, name, address, postal, region, mapsUrl, mgmt, isNew }
//
// Regions (URA-inspired 5-zone split):
//   • Central:  Orchard, Newton, Novena, Toa Payoh, Bukit Timah, etc.
//   • South:    CBD/Tanjong Pagar/Outram/Tiong Bahru/Telok Blangah
//   • East:     Bedok, Tampines, Pasir Ris, Marine Parade, Geylang
//   • North:    Yishun, Woodlands, Sembawang, Hougang, Sengkang,
//               Punggol, AMK, Bishan, Serangoon (incl. Northeast)
//   • West:     Jurong, Clementi, Bukit Batok, Bukit Panjang,
//               Holland, Pasir Panjang, West Coast, Queenstown

const fs = require('fs');
const path = require('path');

const MD_PATH = path.join(__dirname, 'data', 'list-of-hawker-centres.md');
// v0.60.40 — optional lat/lng JSON keyed by name (case-insensitive).
// v0.60.46 — vault now does a normalised-token fallback when the
// exact name match misses. The seed JSON in data/hawker-coords.json
// uses friendly names from data.gov.sg / hawker-centres.json (e.g.
// "Old Airport Road Food Centre"); the canonical NEA list in
// data/list-of-hawker-centres.md uses formal building-block names
// (e.g. "Blk 51 Old Airport Road"). The fuzzy fallback drops filler
// tokens (centre/market/food/blk/road/etc.) so both forms hash to
// the same canonical key.
//
// Generated by `node scripts/fetch-hawker-coords.js` and committed to
// repo. Schema: { "Adam Food Centre": { lat: 1.32, lng: 103.81 }, ... }.
// Source: data.gov.sg public hawker centres dataset
// (resource_id=d_4a086da0a5553be1d89383cd90d07ecd).
// Missing file → centres ship without coords (TMA falls back to the
// per-centre Google Maps URL).
const COORDS_PATH = path.join(__dirname, 'data', 'hawker-coords.json');
// v0.60.59 — optional per-centre stall count + operating status,
// derived from the data.gov.sg "Hawker Centres (GEOJSON)" dataset by
// scripts/fetch-hawker-stalls.js. Replaces the v0.60.53 closures path
// (NEA retired the closures dataset; the same resource id was reused
// for this richer GeoJSON).
// Schema: { "Maxwell Food Centre": { stalls: 64, status: "Existing" }, ... }
// Missing file → centres ship without stall metadata.
const STALLS_PATH = path.join(__dirname, 'data', 'hawker-stalls.json');
// v0.62.595 — NEA quarterly cleaning + renovation closures (built from
// data/hawker-cleaning-closures-2026.csv by scripts/build-hawker-closures.js).
// Also carries fresher 2026 stall counts + status, which override the older
// hawker-stalls.json values when a centre matches (operator: refresh the vault).
const CLOSURES_PATH = path.join(__dirname, 'data', 'hawker-closures.json');
// v0.62.296 — official NEA "Hawker Centres (GEOJSON)" raw file. We join its
// canonical `NAME` (e.g. "Adam Road Food Centre") to our centres BY POSTAL CODE
// so the card title shows the proper NEA name instead of the block-style MD name
// ("Adam Food Centre" / "Blk 1 Jalan Kukoh"). Memoised postal→NAME map; a missing
// file or unmatched postal falls back to the MD name (no display change). 98% of
// the 123 MD rows match by postal. We expose this as `displayName` and KEEP `name`
// untouched so the coords / stalls name-joins stay intact.
const GEOJSON_PATH = path.join(__dirname, 'geoloc', 'HawkerCentresGEOJSON.geojson');
let _geoNameByPostal = null;
function geoNameByPostal() {
  if (_geoNameByPostal) return _geoNameByPostal;
  _geoNameByPostal = new Map();
  try {
    const geo = JSON.parse(fs.readFileSync(GEOJSON_PATH, 'utf8'));
    for (const f of (geo.features || [])) {
      const p = f && f.properties;
      if (p && p.ADDRESSPOSTALCODE && p.NAME) {
        _geoNameByPostal.set(String(p.ADDRESSPOSTALCODE).trim(), String(p.NAME).trim());
      }
    }
  } catch { /* missing/invalid → empty map → MD names used */ }
  return _geoNameByPostal;
}
const REGIONS = ['Central', 'South', 'East', 'North', 'West'];

// Geography-keyword → region. Strong-signal place names that override
// the postal-sector heuristic. Order matters — first match wins.
const REGION_KEYWORDS = [
  ['East', /\b(bedok|tampines|pasir ris|changi|loyang|marine parade|katong|joo chiat|amber|haig|dunman|east coast|geylang serai|geylang bahru|eunos|kembangan|paya lebar|aljunied|sims|jalan eunos|kallang|old airport|ubi)\b/],
  ['North', /\b(yishun|woodlands|sembawang|marsiling|admiralty|canberra|mandai|kranji|sungei kadut|hougang|serangoon|sengkang|punggol|anchorvale|compassvale|buangkok|fernvale|kovan|chomp chomp|ang mo kio|amk|bishan|braddell|seletar|defu|sembawang hills|thomson)\b/],
  ['West', /\b(jurong|clementi|bukit batok|boon lay|choa chu kang|pioneer|tuas|lakeside|bukit panjang|senja|tengah|teban|hillview|west coast|pasir panjang|holland|ghim moh|buona vista|dover|queenstown|commonwealth|tanglin halt|margaret drive|empress|alexandra|mei chin)\b/],
  ['South', /\b(tanjong pagar|chinatown|outram|marina|anson|raffles|cecil|shenton|amoy|telok ayer|maxwell|club street|tiong bahru|bukit merah|telok blangah|harbourfront|redhill|henderson|cantonment|new market|smith street|hong lim|people'?s park|jalan kukoh|havelock|beo crescent|bukit purmei|kreta ayer)\b/],
  ['Central', /\b(orchard|newton|novena|toa payoh|adam|cluny|stevens|farrer|whampoa|balestier|moulmein|macpherson|cambridge|jalan besar|tekka|little india|bras basah|bugis|beach road|north bridge|city hall|bendemeer|berseh|crawford|rochor|sungei road|tanglin(?! halt)|nassim|grange|bukit timah(?! market))\b/]
];

// Postal-sector fallback (first 2 digits of 6-digit code).
function regionFromPostalSector(postal) {
  const sector = parseInt(String(postal || '').slice(0, 2), 10);
  if (!Number.isFinite(sector)) return null;
  if (sector >= 1 && sector <= 8) return 'South';
  if (sector >= 9 && sector <= 10) return 'South';
  if (sector >= 11 && sector <= 13) return 'West';
  if (sector >= 14 && sector <= 16) return 'South';
  if (sector >= 17 && sector <= 23) return 'Central';
  if (sector >= 24 && sector <= 30) return 'Central';
  if (sector >= 31 && sector <= 37) return 'Central';
  if (sector >= 38 && sector <= 52) return 'East';
  if (sector >= 53 && sector <= 57) return 'North';
  if (sector >= 58 && sector <= 71) return 'West';
  if (sector >= 72 && sector <= 80) return 'North';
  if (sector >= 81 && sector <= 82) return 'East';
  return null;
}

function regionForCentre(centre) {
  const text = `${centre.name || ''} ${centre.address || ''}`.toLowerCase();
  for (const [region, re] of REGION_KEYWORDS) {
    if (re.test(text)) return region;
  }
  return regionFromPostalSector(centre.postal) || 'Central';
}

// Parse the MD file's two markdown tables (Markets/Hawker Centres + New
// Hawker Centres) into a flat list. Tolerates the "# tenancies" footnote
// marker on names. Skips closed centres without addresses.
function parseMd(md) {
  if (!md) return [];
  const out = [];
  const lines = md.split(/\r?\n/);
  let inTable = false;
  let isNewSection = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Section heading detect
    if (/^##\s+New Hawker Centres/i.test(line)) {
      isNewSection = true;
      inTable = false;
      continue;
    }
    if (/^##\s+Markets/i.test(line)) {
      isNewSection = false;
      inTable = false;
      continue;
    }
    // Table row detection: starts with "|" and has at least 3 pipes.
    if (line.startsWith('|') && (line.match(/\|/g) || []).length >= 4) {
      const cells = line.split('|').map((s) => s.trim());
      // Drop leading/trailing empty cells from "| ... |" form.
      const trimmed = cells.slice(1, -1);
      // Skip header row + separator row (---).
      if (/^---+$|^-+:?$|^:?-+:?$/.test(trimmed[0] || '')) { inTable = true; continue; }
      if (/^s\/?no$/i.test(trimmed[0] || '')) continue;
      const sno = parseInt(trimmed[0], 10);
      if (!Number.isFinite(sno)) continue;
      const rawName = String(trimmed[1] || '').trim();
      const address = String(trimmed[2] || '').trim();
      const mgmt = String(trimmed[3] || '').trim();
      // v0.62.596 — operator: SHOW redevelopment centres (Bukit Timah Market) with a
      // "Redevelopment till …" tab + black pin instead of hiding them. Coords come from
      // the closure CSV (below), since hawker-coords.json has none for a closed centre.
      // (was: `if (/closed for redevelopment/i.test(address)) continue;`)
      // Strip the "#" footnote marker from the name.
      const name = rawName.replace(/\s*#\s*$/, '').replace(/\s+/g, ' ').trim();
      // Postal: pull "S(NNNNNN)" or "S(NNNNNN/NNNNNN)" — keep the first 6-digit code.
      const m = address.match(/S\((\d{6})/);
      const postal = m ? m[1] : null;
      const centre = { sno, name, address, postal, mgmt, isNew: isNewSection };
      // v0.62.296 — canonical NEA display name (by postal), MD name as fallback.
      centre.displayName = (postal && geoNameByPostal().get(postal)) || name;
      centre.region = regionForCentre(centre);
      centre.mapsUrl = mapsUrlForCentre(centre);
      out.push(centre);
    }
  }
  return out;
}

function mapsUrlForCentre(centre) {
  if (!centre || !centre.name) return '';
  // Use full name + address — Maps resolves to the centre much more
  // reliably than "<name> Singapore" alone.
  const query = centre.address
    ? `${centre.name}, ${centre.address}`
    : `${centre.name} Singapore`;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}

// Module-load cache. The MD file lives in the repo so a single read
// at process start is fine — no Redis, no TTL, no async.
let _allCentres = null;
let _byRegion = null;
// v0.60.40 — load hawker-coords.json (best-effort) and merge lat/lng
// into centres by case-insensitive name match. Two passes: exact name,
// then a token-set normalised fallback for variant spellings (e.g.
// "Adam Food Centre" vs "Adam Road Food Centre").
// v0.60.46 — normalise hawker-centre name to a token-set canonical
// form. Drops filler words (centre/market/food/blk/road etc.) and
// punctuation so "Old Airport Road Food Centre" and "Blk 51 Old
// Airport Road" hash to the same key ("old airport").
function _normaliseHawkerName(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[.,()/\\\-]/g, ' ')
    .replace(/\b(blk|block|blks|centre|center|market|food|hawker|complex|cooked|stalls?|drive|road|rd|street|st|avenue|ave|lane|ln|the|of|at)\b/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function loadCoords() {
  try {
    const raw = fs.readFileSync(COORDS_PATH, 'utf8');
    const parsed = JSON.parse(raw);
    // Build two indexes: exact lowercase, and normalised-token form.
    // Vault loader tries exact first, falls back to normalised so
    // friendly names from data.gov.sg match canonical NEA "Blk N …"
    // names (and vice versa).
    const exact = {};
    const normalised = {};
    for (const [k, v] of Object.entries(parsed || {})) {
      if (v && Number.isFinite(v.lat) && Number.isFinite(v.lng)) {
        const lc = String(k).toLowerCase().trim();
        const co = { lat: v.lat, lng: v.lng };
        exact[lc] = co;
        const norm = _normaliseHawkerName(k);
        if (norm && !normalised[norm]) normalised[norm] = co;
      }
    }
    return { exact, normalised };
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.warn('[HawkerVault] coords load failed:', err.message);
    }
    return { exact: {}, normalised: {} };
  }
}

function loadStalls() {
  try {
    const raw = fs.readFileSync(STALLS_PATH, 'utf8');
    const parsed = JSON.parse(raw);
    const exact = {};
    const normalised = {};
    for (const [k, v] of Object.entries(parsed || {})) {
      if (!v) continue;
      const stalls = Number.isFinite(v.stalls) && v.stalls > 0 ? Math.round(v.stalls) : null;
      const status = typeof v.status === 'string' && v.status.trim() ? v.status.trim() : null;
      if (stalls == null && !status) continue;
      const obj = { stalls, status };
      const lc = String(k).toLowerCase().trim();
      exact[lc] = obj;
      const norm = _normaliseHawkerName(k);
      if (norm && !normalised[norm]) normalised[norm] = obj;
    }
    return { exact, normalised };
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.warn('[HawkerVault] stalls load failed:', err.message);
    }
    return { exact: {}, normalised: {} };
  }
}

// v0.62.595 — cleaning + renovation closures (and fresh 2026 stall/status). Same
// exact + normalised-token index pair as loadStalls, so the CSV's formal NEA names
// reconcile with the vault's canonical names.
function loadClosures() {
  try {
    const raw = fs.readFileSync(CLOSURES_PATH, 'utf8');
    const parsed = JSON.parse(raw);
    const exact = {};
    const normalised = {};
    const byPostal = {};   // the reliable join key (name-folding alone misses ~70%)
    for (const [k, v] of Object.entries(parsed || {})) {
      if (!v) continue;
      const lc = String(k).toLowerCase().trim();
      exact[lc] = v;
      const norm = _normaliseHawkerName(k);
      if (norm && !normalised[norm]) normalised[norm] = v;
      if (v.postal && !byPostal[v.postal]) byPostal[v.postal] = v;
    }
    return { exact, normalised, byPostal };
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.warn('[HawkerVault] closures load failed:', err.message);
    }
    return { exact: {}, normalised: {}, byPostal: {} };
  }
}

// v0.62.553 — operator: tag centres that contain Michelin Bib Gourmand stalls.
// The mapping already exists in SG-michelin.js: each BIB_GOURMAND entry is
// { name (stall), address (hawker-centre name), category:'bib-gourmand' } — so
// `address` IS the centre name. Build a normalised-token index (drops
// Centre/Market/Food/Road/… so "Adam Food Centre" ~ "Adam Road Food Centre"),
// keyed the same way as the coords/stalls joins. Entries with an empty/street
// `address` (standalone restaurants) are skipped — they aren't in a centre.
// v0.62.553 — the Bib `address` fields drop the block number the vault names
// carry (Bib "Old Airport Road Food Centre" vs vault "Blk 51 Old Airport Road"),
// so the bib key is _normaliseHawkerName PLUS standalone-number stripping. This
// stays a deterministic TOKEN match (no fuzzy edit-distance) — findByName's
// edit-distance produced false positives (Jurong West 505 → Jurong West Hawker
// Centre; both Redhill entries → one Blk 79 centre), which we deliberately avoid.
function _bibKey(s) {
  return _normaliseHawkerName(s).replace(/\b\d+\b/g, ' ').replace(/\s+/g, ' ').trim();
}
function _bibDigits(s) {
  return String(s || '').match(/\d+/g) || [];
}
// Map<bibKey, Array<{ stall, digits }>>. The digits list guards block-number
// collisions in the join (e.g. "Clementi 448" must not tag Blk 353 Clementi).
let _bibIndex;
function loadBibIndex() {
  if (_bibIndex) return _bibIndex;
  _bibIndex = new Map();
  try {
    const { getBibGourmand } = require('./SG-michelin');
    for (const e of (getBibGourmand() || [])) {
      const addr = e && typeof e.address === 'string' ? e.address.trim() : '';
      const stall = e && typeof e.name === 'string' ? e.name.trim() : '';
      if (!addr || !stall) continue;
      const norm = _bibKey(addr);
      if (!norm) continue;
      if (!_bibIndex.has(norm)) _bibIndex.set(norm, []);
      _bibIndex.get(norm).push({ stall, digits: _bibDigits(addr) });
    }
  } catch (err) {
    console.warn('[HawkerVault] SG-michelin bib load failed:', err.message);
  }
  return _bibIndex;
}

function loadAll() {
  if (_allCentres) return _allCentres;
  try {
    const md = fs.readFileSync(MD_PATH, 'utf8');
    _allCentres = parseMd(md);
    // v0.60.40 — attach lat/lng from hawker-coords.json when available.
    // v0.60.46 — two-pass match: exact lowercase, then normalised-token
    // fallback (drops "Blk N", "Centre", "Food", "Market", etc.) so the
    // friendly seed names align with canonical NEA building-block names.
    const { exact, normalised } = loadCoords();
    if (Object.keys(exact).length || Object.keys(normalised).length) {
      let hits = 0;
      for (const c of _allCentres) {
        const lc = String(c.name || '').toLowerCase().trim();
        let co = exact[lc];
        if (!co) {
          const norm = _normaliseHawkerName(c.name || '');
          if (norm) co = normalised[norm];
        }
        if (co) {
          c.lat = co.lat;
          c.lng = co.lng;
          hits++;
        }
      }
      console.log(`[HawkerVault] coords: ${hits}/${_allCentres.length} centres geocoded`);
    }
    // v0.60.59 — attach stall count + operating status when known
    // (data.gov.sg "Hawker Centres (GEOJSON)" via fetch-hawker-stalls.js).
    const stalls = loadStalls();
    if (Object.keys(stalls.exact).length || Object.keys(stalls.normalised).length) {
      let shits = 0;
      for (const c of _allCentres) {
        const lc = String(c.name || '').toLowerCase().trim();
        let s = stalls.exact[lc];
        if (!s) {
          const norm = _normaliseHawkerName(c.name || '');
          if (norm) s = stalls.normalised[norm];
        }
        if (s) {
          if (s.stalls != null) c.stalls = s.stalls;
          if (s.status) c.status = s.status;
          shits++;
        }
      }
      console.log(`[HawkerVault] stalls: ${shits}/${_allCentres.length} centres with stall metadata`);
    }
    // v0.62.595 — attach cleaning/renovation closure windows (client shows a tab
    // when TODAY falls inside one) AND refresh stall count / status / (new) flag
    // from the fresher 2026 CSV (operator: refresh the vault). The closure merge
    // runs AFTER loadStalls so the 2026 values override the older hawker-stalls.json.
    const closures = loadClosures();
    if (Object.keys(closures.byPostal).length || Object.keys(closures.exact).length) {
      let chits = 0;
      for (const c of _allCentres) {
        // Postal is the reliable key; fall back to exact then normalised name.
        let z = c.postal ? closures.byPostal[String(c.postal).trim()] : null;
        if (!z) {
          const lc = String(c.name || '').toLowerCase().trim();
          z = closures.exact[lc];
        }
        if (!z) {
          const norm = _normaliseHawkerName(c.name || '');
          if (norm) z = closures.normalised[norm];
        }
        if (!z) continue;
        chits++;
        const cleaning = Array.isArray(z.cleaning) ? z.cleaning : [];
        const renovation = Array.isArray(z.renovation) ? z.renovation : [];
        const redevelopment = Array.isArray(z.redevelopment) ? z.redevelopment : [];   // v0.62.596
        if (cleaning.length || renovation.length || redevelopment.length) c.closures = { cleaning, renovation, redevelopment };
        if (Number.isFinite(z.foodStalls) && z.foodStalls > 0) c.stalls = z.foodStalls;   // 2026 refresh
        // v0.62.912 — the MARKET half of a market-and-food centre. Measured on 83 of 123, and
        // dropped here until now, so those centres read at roughly half their real size: Blk 117
        // Aljunied is 79 cooked-food stalls AND 82 market stalls, and the card said 79.
        if (Number.isFinite(z.marketStalls) && z.marketStalls > 0) c.marketStalls = z.marketStalls;
        // v0.62.912 — NEA's prose profile, present for all 123. See build-hawker-closures.js.
        if (z.description) c.description = z.description;
        if (z.status) c.status = z.status;
        if (z.isNew) c.isNew = true;
        // v0.62.596 — coord fallback from the closure CSV for centres missing from
        // hawker-coords.json (e.g. Bukit Timah, redevelopment) so they still get a pin.
        if ((!Number.isFinite(c.lat) || !Number.isFinite(c.lng)) && Number.isFinite(z.lat) && Number.isFinite(z.lng)) {
          c.lat = z.lat; c.lng = z.lng;
        }
      }
      console.log(`[HawkerVault] closures: ${chits}/${_allCentres.length} centres with closure/2026 metadata`);
    }
    // v0.62.553 — attach Bib Gourmand stall names (number-stripped token match
    // + digit-consistency guard: a bib address carrying a block number only tags
    // a centre whose name contains that number).
    const bib = loadBibIndex();
    if (bib.size) {
      let bhits = 0;
      for (const c of _allCentres) {
        const norm = _bibKey(c.name || '');
        const entries = norm ? bib.get(norm) : null;
        if (!entries || !entries.length) continue;
        const cd = new Set(_bibDigits(c.name || ''));
        const names = [];
        for (const e of entries) {
          if (e.digits.length && !e.digits.every((d) => cd.has(d))) continue;
          if (!names.includes(e.stall)) names.push(e.stall);
        }
        if (names.length) { c.bibStalls = names; bhits++; }
      }
      console.log(`[HawkerVault] bib-gourmand: ${bhits}/${_allCentres.length} centres tagged`);
    }
  } catch (err) {
    console.warn('[HawkerVault] MD load failed:', err.message);
    _allCentres = [];
  }
  return _allCentres;
}

function getAllCentres() {
  return loadAll();
}

function getByRegion(region) {
  if (!_byRegion) {
    _byRegion = {};
    for (const r of REGIONS) _byRegion[r] = [];
    for (const c of loadAll()) {
      if (_byRegion[c.region]) _byRegion[c.region].push(c);
    }
    for (const r of REGIONS) {
      _byRegion[r].sort((a, b) => a.name.localeCompare(b.name, 'en', { sensitivity: 'base' }));
    }
  }
  if (!region) return _byRegion;
  return _byRegion[region] || [];
}

// Format a single region's centres as a Telegram-friendly Markdown
// list. Each line: "1. *Name* — [📍 Maps](url)\n   address". Capped
// to fit Telegram's 4096-char message limit.
function formatRegionList(region) {
  const list = getByRegion(region);
  if (!Array.isArray(list) || !list.length) return `_No hawker centres found in ${region}._`;
  const lines = [`*${region} — ${list.length} hawker centres* (alphabetical)\n`];
  list.forEach((c, i) => {
    lines.push(`${i + 1}. *${c.name}*${c.isNew ? ' 🆕' : ''}`);
    if (c.address) lines.push(`   ${c.address}`);
    if (c.mapsUrl) lines.push(`   📍 ${c.mapsUrl}`);
  });
  let out = lines.join('\n');
  if (out.length > 3800) out = out.slice(0, 3700) + '\n\n_…truncated; ' + (list.length) + ' total in this region._';
  return out;
}

function formatRegionSummary() {
  const by = getByRegion();
  const total = loadAll().length;
  const parts = REGIONS.map((r) => `*${r}*: ${by[r]?.length || 0}`);
  return `🍚 *${total} hawker centres* (snapshot 25 Jul 2025)\n\n${parts.join(' · ')}`;
}

// ---------- v0.49.0 fuzzy-match helpers (kept for nea-scrape consumers) ----------

function normaliseName(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[.,()/\\-]/g, ' ')
    .replace(/\b(centre|center|market|food|hawker|complex|cooked)\b/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function editDistance(a, b) {
  if (!a || !b) return Math.max(a?.length || 0, b?.length || 0);
  if (a === b) return 0;
  const m = a.length;
  const n = b.length;
  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));
  for (let i = 0; i <= m; i++) dp[i][0] = i;
  for (let j = 0; j <= n; j++) dp[0][j] = j;
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      dp[i][j] = Math.min(dp[i - 1][j] + 1, dp[i][j - 1] + 1, dp[i - 1][j - 1] + cost);
    }
  }
  return dp[m][n];
}

function findByName(centresOrQuery, maybeQuery) {
  // Backward-compat: callers can pass (centresArray, query) OR just (query)
  // where centres are loaded from the vault automatically.
  let centres, query;
  if (Array.isArray(centresOrQuery)) { centres = centresOrQuery; query = maybeQuery; }
  else { centres = loadAll(); query = centresOrQuery; }
  if (!Array.isArray(centres) || !centres.length || !query) return null;
  const qn = normaliseName(query);
  if (!qn) return null;
  let best = null;
  for (const c of centres) {
    const cn = normaliseName(c.name);
    if (!cn) continue;
    if (cn === qn) return { centre: c, score: 1, distance: 0 };
    if (cn.includes(qn) || qn.includes(cn)) {
      const score = Math.min(qn.length, cn.length) / Math.max(qn.length, cn.length);
      if (!best || score > best.score) best = { centre: c, score, distance: 0 };
      continue;
    }
    const d = editDistance(qn, cn);
    const maxLen = Math.max(qn.length, cn.length);
    if (maxLen === 0) continue;
    const ratio = 1 - d / maxLen;
    if (ratio >= 0.75 && (!best || ratio > best.score)) {
      best = { centre: c, score: ratio, distance: d };
    }
  }
  return best;
}

function annotateNames(centresOrNames, maybeNames) {
  let centres, names;
  if (Array.isArray(maybeNames)) { centres = centresOrNames; names = maybeNames; }
  else { centres = loadAll(); names = centresOrNames; }
  if (!Array.isArray(names)) return [];
  return names.map((n) => ({ input: n, match: findByName(centres, n) }));
}

// Reset module-level cache (for tests).
function _resetCache() {
  _allCentres = null;
  _byRegion = null;
}

module.exports = {
  MD_PATH,
  REGIONS,
  parseMd,
  regionForCentre,
  regionFromPostalSector,
  getAllCentres,
  getByRegion,
  formatRegionList,
  formatRegionSummary,
  mapsUrlForCentre,
  normaliseName,
  editDistance,
  findByName,
  annotateNames,
  _resetCache
};
