// prompt-locale.js — v0.62.839
//
// The language instruction handed to the model, for any locale the app supports.
//
// THE BUG THIS CLOSES, AND WHY IT LOOKED LIKE A DIFFERENT ONE. Operator, from a
// Japanese session over Tokyo: "wateriest are english" — the eateries' dish lines
// read `おすすめ: lobster cream pasta • crab arrabiata • tiramisu`. The LABEL was
// Japanese and the content it labelled was not, which reads like a missing
// translation and is not one. Every prompt that told the model what language to
// write in was shaped `lang === 'fr' ? <a French instruction> : ''` — so French got
// an instruction, English needed none, and the other SIX locales got an empty
// string and therefore English prose. Seven sites, all the same shape:
// pipeline.js x2 (vibe / dishes / signature_dish), gemini-client.js x3 (chat reply,
// hidden-gems narration, dish explainer), vibe-summary.js x2 (review summary).
//
// This is NOT O-337. That item is about Google Places DATA — `venue.name`, the
// romaji address — which costs money to re-request and carries the display-vs-key
// hazard because the name doubles as a Maps query and a DOM id. This is our own
// narration, generated by our own prompt, and localising it costs nothing.
//
// ONE MODULE, SEVEN CALLERS, deliberately. A short language rule duplicated at
// seven sites is the shape that produced this bug in the first place: whoever added
// the French block added it where they needed it, and the other six sites — and the
// other six locales — were never revisited. `langName()` already maps all eight
// (and 27 more) in translate-review.js, so nothing new is invented here.
//
// WHAT IS DELIBERATELY PRESERVED. The French block protected iconic Singapore dish
// names from being translated — "laksa" must stay "laksa", not become "soupe de
// nouilles épicée". That is not French-specific politeness: a translated dish name
// matches nothing the user could search for, and it erases the name the dish
// actually has. So every locale inherits the protection France already had, which
// is replicating a proven instruction rather than widening the change.

const { langName } = require('./translate-review');

// Kept in one place so the two narration prompts cannot drift apart. This is the
// union of the lists the two French blocks carried, which differed from each other
// — pipeline's Michelin block named seven dishes and its Places block named
// nineteen, for no reason either comment recorded.
const ICONIC_SG_DISHES = [
  'laksa', 'char kway teow', 'kopi-o', 'kaya toast', 'mee siam', 'satay',
  'hokkien mee', 'popiah', 'rojak', 'prata', 'roti john', 'nasi lemak',
  'otah', 'kueh', 'chendol', 'ice kachang', 'kway teow', 'char siew', 'teh tarik',
].join(', ');

// The locales the APP ships, which is not the same as the locales `langName()` can
// name. That distinction is load-bearing: `langName('kr')` returns the uppercase
// fallback 'KR' — 'kr' is not an ISO code, Korean is 'ko' — so gating on "langName
// returned something" would tell the model to write in "KR". Caught by exercising
// this function rather than by reading it. Korean is parked as a ninth locale; when
// it lands it is one entry here, and `langName` already knows 'ko'.
const APP_LOCALES = ['en', 'fr', 'id', 'ru', 'de', 'zh', 'ja', 'es', 'ko'];

/**
 * True when the model needs telling. English is the prompts' own language, so it
 * needs no instruction — and an unsupported locale gets none rather than a guess.
 * @param {string} [lang]
 * @returns {boolean}
 */
function needsLocalisation(lang) {
  return APP_LOCALES.includes(lang) && lang !== 'en';
}

/**
 * The LOCALISATION block for a venue-narration prompt (vibe / dishes /
 * signature_dish). Returns '' for English or an unknown locale, so callers can
 * interpolate it unconditionally exactly as they did the French-only version.
 * @param {string} [lang]
 * @returns {string}
 */
function narrationLocalisation(lang) {
  if (!needsLocalisation(lang)) return '';
  const name = langName(lang);
  return `\nLOCALISATION: write all "vibe", "dishes", and "signature_dish" strings in ${name.toUpperCase()}. `
    + `Keep iconic Singapore dish names in their ORIGINAL form, untranslated (${ICONIC_SG_DISHES}). `
    + `Translate the descriptive prose around them. Numbers, prices and placeIds stay raw.\n`;
}

/**
 * The one-line reply-language instruction for a conversational prompt.
 * Dish names, cuisine labels and any Places search term stay English, because they
 * are looked up, not read — the same carve-out the French line already made.
 * @param {string} [lang]
 * @returns {string}
 */
function replyLanguageLine(lang) {
  if (!needsLocalisation(lang)) return 'Reply in English (en).';
  const name = langName(lang);
  return `Reply in ${name} (${lang}) — clarifying questions and "why" prose. `
    + `Keep dish names, cuisine labels, and Places searchTerm in English.`;
}

/**
 * The instruction for a free-prose field written in the reader's language, where
 * one named field must stay in its original form (e.g. the dish being explained).
 * @param {string} [lang]
 * @param {string} field      the prose field to localise, e.g. 'explainer'
 * @param {string} [keepField] a field to leave in English / its original form
 * @returns {string}
 */
function proseLanguageLine(lang, field, keepField) {
  const keep = keepField
    ? ` Keep the dish name in "${keepField}" in its common English / original form.`
    : '';
  if (!needsLocalisation(lang)) return `Write the "${field}" in English.`;
  return `Write the "${field}" in ${langName(lang)}.${keep}`;
}

/**
 * The language the narration will ACTUALLY be written in, for callers that have to
 * name it rather than instruct it — cache keys, log lines, provenance fields.
 *
 * v0.62.897 — THE EIGHTH SITE. This file's header names seven prompt sites that each
 * wrote `lang === 'fr' ? … : ''` and so gave six locales English prose. It missed an
 * eighth of the same shape that is not a prompt at all: `index.js`'s Michelin enrich
 * CACHE KEY, `michelin:enrich:v2:${csLang === 'fr' ? 'fr' : 'en'}`. v0.62.839 localised
 * the narration and left the key at two, so seven locales began writing their output
 * into one bucket labelled `en` — a Korean reader's Korean vibe line served to the next
 * English reader, and the reverse. A key that says what language a blob is in has to be
 * derived from the same function that decided the language, or it is a second opinion.
 *
 * Returns 'en' exactly when `narrationLocalisation` returns '' — same predicate, so the
 * two cannot drift.
 * @param {string} [lang]
 * @returns {string} an APP_LOCALES code
 */
function narrationLang(lang) {
  return needsLocalisation(lang) ? lang : 'en';
}

module.exports = {
  APP_LOCALES,
  narrationLang,
  ICONIC_SG_DISHES,
  needsLocalisation,
  narrationLocalisation,
  replyLanguageLine,
  proseLanguageLine,
};
